// ============================================
// DICTIONNAIRE FR / EN
// Toutes les chaînes visibles du site, tous thèmes confondus.
// Utilisation : t('cle') depuis le JS, ou data-i18n="cle"
// (data-i18n-html, data-i18n-aria, data-i18n-title) dans le HTML.
// ============================================
const traductions = {
  fr: {
    // ---------- Commun ----------
    'commun.titre-page': 'Dev Gninoue — Portfolio',
    'commun.aller-contenu': 'Aller au contenu',
    'commun.ouvrir-menu': 'Ouvrir le menu',
    'commun.fermer-menu': 'Fermer le menu',
    'commun.nav-principale': 'Navigation principale',
    'commun.nav-pied': 'Liens du pied de page',
    'commun.choisir-langue': 'Choisir la langue',
    'commun.choisir-theme': 'Choisir le thème',
    'commun.whatsapp': 'Me contacter sur WhatsApp',
    'commun.whatsapp-message': 'Bonjour, je vous contacte depuis votre portfolio.',
    'commun.theme-change': 'Thème appliqué : {theme}',
    'commun.langue-change': 'Langue : français',
    'commun.erreur-theme': "Impossible de charger ce thème. Vérifiez votre connexion puis réessayez.",
    'commun.a-venir': 'Bientôt disponible',
    'commun.fermer': 'Fermer',
    'commun.nouvel-onglet': '(nouvel onglet)',

    'nav.accueil': 'Accueil',
    'nav.apropos': 'À propos',
    'nav.competences': 'Compétences',
    'nav.projets': 'Projets',
    'nav.contact': 'Me contacter',

    'theme.professionnel': 'Professionnel',
    'theme.gaming': 'Gaming',
    'theme.personnel': 'Style personnel',
    'theme.description-professionnel': 'Sobre et efficace',
    'theme.description-gaming': 'Un vrai jeu jouable',
    'theme.description-personnel': 'Manga, pixel et néon',

    'footer.droits': 'Tous droits réservés.',
    'footer.cv': 'Télécharger mon CV',
    'footer.cv-demande': 'Demander mon CV',
    'footer.cv-sujet': 'Demande de CV',
    'footer.credits': 'Icônes Font Awesome (CC BY 4.0) · Polices Google Fonts (OFL)',

    // ---------- Contenu partagé ----------
    'profil.role-court': 'Développeur Full Stack junior',
    'apropos.titre': 'À propos de moi',
    'apropos.p1': "Passionné par l'informatique et les jeux vidéo depuis l'enfance, j'ai naturellement choisi de transformer cette passion en véritable projet professionnel. Après l'obtention de mon baccalauréat, j'ai intégré la filière Informatique et Génie Logiciel, où je poursuis actuellement ma deuxième année de licence.",
    'apropos.p2': "En tant que développeur Full Stack junior, je conçois et développe des sites web, des applications et des bases de données, de la conception à la mise en production. J'aime transformer des idées en solutions concrètes, fonctionnelles et intuitives.",
    'apropos.p3': "Au-delà du développement, je m'intéresse au graphisme, à la modélisation 3D, au montage vidéo et à la maintenance informatique. Ces compétences, que je développe en complément de la programmation, me permettent de créer des projets plus complets, à la croisée de la technologie, de la créativité et de la technique.",
    'apropos.etudes': 'Licence 2 · Informatique et Génie Logiciel',
    'apropos.objectif': 'Objectif : devenir expert en développement de jeux vidéo',
    'apropos.chiffre-competences': 'Compétences',
    'apropos.chiffre-projets': 'Projets',
    'apropos.chiffre-annees': "Ans d'expérience",

    'competences.titre': 'Mes compétences',
    'competences.niveau': 'Niveau :',
    'niveau.debutant': 'Débutant',
    'niveau.intermediaire': 'Intermédiaire',
    'niveau.expert': 'Expert',
    'categorie.web': 'Web',
    'categorie.logiciel': 'Logiciel et mobile',
    'categorie.jeu': 'Jeu vidéo et 3D',
    'categorie.creation': 'Création visuelle',
    'categorie.outil': 'Outils',
    'categorie.tout': 'Tout',
    'categorie.ia': 'IA',

    'projets.titre': 'Mes projets réalisés',
    'projets.code': 'Code',
    'projets.demo': 'Démo',
    'projets.code-prive': 'Code privé',
    'projets.termine': 'Terminé',
    'projets.vedette': 'Projet phare',
    'projets.encours': 'En cours',
    'projets.filtrer': 'Filtrer les projets',
    'projets.voir-github': 'Voir tout sur GitHub',
    'projets.capture-a-venir': 'Capture à venir',

    'contact.titre': 'Me contacter',
    'contact.sous-titre': 'Un stage, un projet, une idée ? Écrivez-moi, je réponds vite.',
    'contact.dispo': 'Disponible pour tout type de stage, ainsi que pour des entretiens et des projets freelance.',
    'contact.localisation': 'Localisation',
    'contact.formulaire-titre': "M'envoyer un message",
    'contact.label-nom': 'Nom',
    'contact.label-email': 'Email',
    'contact.label-message': 'Message',
    'contact.placeholder-nom': 'Votre nom',
    'contact.placeholder-email': 'vous@exemple.com',
    'contact.placeholder-message': 'Bonjour Jean-Marc, ...',
    'contact.bouton-envoyer': 'Envoyer le message',
    'contact.envoi-cours': 'Envoi en cours...',
    'contact.succes': 'Message envoyé avec succès, merci !',
    'contact.erreur': "Une erreur s'est produite. Réessayez ou écrivez-moi directement par email.",
    'contact.email': 'Email',
    'contact.whatsapp': 'WhatsApp',
    'contact.github': 'GitHub',

    // ---------- Thème Professionnel ----------
    'pro.salutation': 'Bienvenue sur mon portfolio',
    'pro.jesuis': 'Je suis',
    'pro.role': 'Développeur <span class="role-accent">Full Stack</span> Junior',
    'pro.accroche': 'Je conçois des sites, des applications et des jeux, du premier croquis à la mise en ligne.',
    'pro.langage': 'Langage favori :',
    'pro.bouton-projets': 'Voir mes projets',
    'pro.bouton-contact': 'Me contacter',
    'pro.badge-experience': "Ans d'expérience",
    'pro.badge-projets': 'Projets réalisés',
    'pro.photo-alt': 'Photo de Gninoue Jean-Marc',
    'pro.defiler': 'Défiler vers la suite',
    'pro.essayer-theme': 'Envie de voir autre chose ?',
    'pro.essayer-theme-texte': 'Ce portfolio existe en trois versions. Essayez-en une autre :',
    'pro.essayer-bouton': 'Essayer un autre thème du portfolio',
    // ---------- Thème Gaming : L'Île des Fragments ----------
    'jeu.titre': "L'Île des Fragments",
    'jeu.sous-titre': 'Un portfolio jouable de Dev Gninoue',
    'jeu.intro': "La nuit a englouti l'île. Rallume-la en retrouvant les quatre fragments du portfolio.",
    'jeu.jouer': 'Jouer',
    'jeu.continuer': 'Continuer',
    'jeu.nouvelle-partie': 'Nouvelle partie',
    'jeu.mode-lecture': 'Passer le jeu / Mode lecture',
    'jeu.mode-lecture-court': 'Mode lecture',
    'jeu.retour-jeu': 'Retour au jeu',
    'jeu.chargement': "Chargement de l'île...",
    'jeu.duree': 'Environ 5 minutes · progression sauvegardée',
    'jeu.controles': 'Commandes',
    'jeu.controles-clavier': 'ZQSD, WASD ou flèches : se déplacer · Maj : courir · E ou Espace : interagir · Échap : pause',
    'jeu.controles-souris': 'Souris : cliquer pour se déplacer ou interagir',
    'jeu.controles-tactile': 'Tactile : glisser pour bouger, toucher pour interagir',
    'jeu.mouvement-reduit': 'Animations réduites : secousses et flashs désactivés.',
    'jeu.libelle-canevas': "L'Île des Fragments, jeu d'exploration. Le bouton Mode lecture donne accès à tout le contenu sans jouer.",
    'jeu.son': 'Son',
    'jeu.son-active': 'Son activé',
    'jeu.son-coupe': 'Son coupé',
    'jeu.pause': 'Pause',
    'jeu.reprendre': 'Reprendre',
    'jeu.recommencer': 'Recommencer',
    'jeu.confirmer-recommencer': 'Cliquer encore pour tout effacer',
    'jeu.changer-theme': 'Changer de thème',
    'jeu.suivant': 'Suivant',
    'jeu.fermer': 'Fermer',
    'jeu.fragments': 'fragments',
    'jeu.fragment-histoire': 'Histoire',
    'jeu.fragment-savoir': 'Savoir',
    'jeu.fragment-oeuvres': 'Œuvres',
    'jeu.fragment-lien': 'Lien',
    'jeu.fragment-obtenu': 'Fragment obtenu : {nom} ({n}/4)',
    'jeu.obtenu': 'obtenu',
    'jeu.manquant': 'pas encore obtenu',
    'jeu.orbes': 'Orbes de compétences',
    'jeu.steles': 'Stèles de projets',
    'jeu.objectif-village': "Parle à l'Archiviste du Village des Mémoires (À propos)",
    'jeu.objectif-foret': 'Récolte les orbes de la Forêt des Savoirs (Compétences)',
    'jeu.objectif-ruines': 'Éveille les stèles des Ruines des Œuvres (Projets)',
    'jeu.objectif-boss': 'Le dôme est brisé : affronte le Grand Bug au Cap du Phare',
    'jeu.objectif-fin': "L'île est sauvée ! Le phare t'attend pour contacter Dev",
    'jeu.zone-camp': 'Le Feu de Camp',
    'jeu.zone-camp-sous': 'Point de départ',
    'jeu.zone-village': 'Le Village des Mémoires',
    'jeu.zone-village-sous': 'À propos',
    'jeu.zone-foret': 'La Forêt des Savoirs',
    'jeu.zone-foret-sous': 'Compétences',
    'jeu.zone-ruines': 'Les Ruines des Œuvres',
    'jeu.zone-ruines-sous': 'Projets',
    'jeu.zone-arene': 'Le Cap du Phare',
    'jeu.zone-arene-sous': 'Contact',
    'jeu.nom-panneau': 'Panneau',
    'jeu.nom-archiviste': "L'Archiviste",
    'jeu.nom-bug': 'Le Grand Bug',
    'jeu.nom-phare': 'Le phare',
    'jeu.panneau-camp': "Bienvenue, voyageur ! L'île de Dev est plongée dans la nuit. Trois fragments t'attendent : le Village au nord-ouest, la Forêt au nord-est et les Ruines au sud-ouest. Si tu te perds, suis la flèche dorée.",
    'jeu.panneau-village': "Village des Mémoires. L'Archiviste y garde l'histoire de Dev.",
    'jeu.panneau-foret': 'Forêt des Savoirs. Chaque orbe lumineuse renferme une compétence de Dev. Ramasse-les toutes !',
    'jeu.panneau-ruines': "Ruines des Œuvres. Chaque stèle garde la mémoire d'un projet : approche-toi et examine-les.",
    'jeu.panneau-arene': 'Cap du Phare. Un dôme de glitchs bloque le passage : il faut trois fragments pour le briser.',
    'jeu.archiviste-1': "Oh ! Une lanterne allumée, enfin. Bienvenue, voyageur. Je suis l'Archiviste : je garde la mémoire de celui qui a façonné cette île.",
    'jeu.archiviste-2': "Il s'appelle Gninoue Jean-Marc. Ici, on l'appelle Dev... et OZEN quand il joue ou monte des vidéos. Écoute son histoire...",
    'jeu.archiviste-fin': "Voilà son histoire. Prends ce fragment : il rendra un peu de lumière à l'île.",
    'jeu.archiviste-retour': "Tu veux réentendre l'histoire de Dev ? Avec plaisir.",
    'jeu.orbe-obtenue': '{nom} · {niveau} ({n}/{total})',
    'jeu.dome-ferme': 'Le dôme résiste. Il manque encore {n} fragment(s).',
    'jeu.dome-ouvert': 'Trois fragments réunis : le dôme du Cap du Phare s\'est brisé !',
    'jeu.bug-1': "Qui ose rallumer la lumière ? Je suis le Grand Bug. J'ai dévoré la lumière de cette île, ligne de code après ligne de code.",
    'jeu.bug-2': 'Tu ne pourras jamais me toucher... à moins de recharger les trois pylônes de lumière. Mais tu n\'oseras pas !',
    'jeu.bug-3': '(Reste près d\'un pylône pour le charger, et esquive les glitchs roses.)',
    'jeu.phare-eteint': 'Le phare est éteint. Le Grand Bug rôde encore autour du cap.',
    'jeu.action-parler': 'Parler',
    'jeu.action-lire': 'Lire',
    'jeu.action-examiner': 'Examiner',
    'jeu.stele-progression': 'Stèle {n} sur {total}',
    'jeu.fin-titre': "L'île est restaurée !",
    'jeu.fin-texte': "Merci d'avoir joué ! Tu connais maintenant Dev : son histoire, ses compétences et ses projets. Il ne reste qu'une chose à faire...",
    'jeu.fin-contact': 'Contacter Dev',
    'jeu.fin-temps': 'Temps',
    'jeu.fin-succes': 'Succès',
    'jeu.continuer-explorer': 'Continuer à explorer',
    'jeu.ecrire': 'Écrire un message',
    'jeu.succes-debloque': 'Succès débloqué : {nom}',
    'jeu.lecture-titre': 'Le portfolio, version texte',
    'jeu.lecture-intro': 'Pas le temps de jouer ? Tout le contenu est ici.',
    'jeu.credits': "L'Île des Fragments : graphismes et sons générés en code · Polices Press Start 2P et Pixelify Sans (OFL)",
    'succes.premier-pas': 'Premier pas',
    'succes.premier-pas-desc': "Faire ses premiers pas sur l'île",
    'succes.bavard': 'Oreille attentive',
    'succes.bavard-desc': "Écouter l'histoire de l'Archiviste",
    'succes.explorateur': 'Explorateur',
    'succes.explorateur-desc': 'Visiter les quatre régions',
    'succes.collectionneur': 'Collectionneur',
    'succes.collectionneur-desc': 'Récolter toutes les orbes',
    'succes.archeologue': 'Archéologue',
    'succes.archeologue-desc': 'Éveiller toutes les stèles',
    'succes.chasseur': 'Chasseur de bugs',
    'succes.chasseur-desc': 'Vaincre le Grand Bug',
    'succes.intouchable': 'Intouchable',
    'succes.intouchable-desc': 'Vaincre le Grand Bug sans être touché',
    'succes.eclair': 'Éclair',
    'succes.eclair-desc': "Terminer l'aventure en moins de 5 minutes",
    // ---------- Thème Style personnel ----------
    'perso.volume': 'Volume',
    'perso.sous-titre': 'Développeur Full Stack, créateur de jeux vidéo et monteur vidéo',
    'perso.commandes': 'whoami --role fullstack|compile --langage c++ --mode passion|render --montage after-effects|git push origin reves',
    'perso.lire-volumes': 'Lire les volumes',
    'perso.ecrire': "M'écrire",
    'perso.bulle-bonjour': 'Bienvenue dans mon univers !',
    'perso.tourner-page': 'Tourner la page',
    'perso.chapitre': 'Chapitre',
    'perso.fiche': 'Fiche personnage',
    'perso.fiche-nom': 'Nom',
    'perso.fiche-classe': 'Classe',
    'perso.fiche-niveau': 'Niveau',
    'perso.fiche-arme': 'Arme favorite',
    'perso.fiche-quete': 'Quête principale',
    'perso.fiche-animes': 'Animes et mangas',
    'perso.fiche-jeux': 'Jeux préférés',
    'perso.fiche-devise': 'Devise',
    'perso.fiche-pseudo': 'Pseudo',
    'perso.fiche-pseudo-valeur': 'OZEN (en jeu et en montage)',
    'perso.fiche-origine': 'Base',
    'perso.fiche-personnalite': 'En une phrase',
    'perso.fiche-tekken': 'Mains Tekken',
    'perso.a-debloquer': 'À débloquer',
    'perso.filtrer-competences': 'Filtrer les compétences',
    'perso.legende': 'Jauge de puissance : trois segments par niveau (débutant, intermédiaire, expert).',
    'perso.intro-volumes': "Chaque projet est un volume de la série. Certains sont terminés, d'autres sont encore en cours de publication.",
    'perso.a-suivre': 'À suivre...',
    'perso.autre-dimension': 'Ce manga existe aussi dans deux autres dimensions :',
    'perso.credits': 'Style personnel : animations GSAP (licence standard GreenSock) · Polices Dela Gothic One, Zen Kaku Gothic New et Share Tech Mono (OFL)'
  },

  en: {
    // ---------- Common ----------
    'commun.titre-page': 'Dev Gninoue — Portfolio',
    'commun.aller-contenu': 'Skip to content',
    'commun.ouvrir-menu': 'Open menu',
    'commun.fermer-menu': 'Close menu',
    'commun.nav-principale': 'Main navigation',
    'commun.nav-pied': 'Footer links',
    'commun.choisir-langue': 'Choose language',
    'commun.choisir-theme': 'Choose theme',
    'commun.whatsapp': 'Contact me on WhatsApp',
    'commun.whatsapp-message': 'Hello, I am reaching out from your portfolio.',
    'commun.theme-change': 'Theme applied: {theme}',
    'commun.langue-change': 'Language: English',
    'commun.erreur-theme': 'Could not load this theme. Check your connection and try again.',
    'commun.a-venir': 'Coming soon',
    'commun.fermer': 'Close',
    'commun.nouvel-onglet': '(new tab)',

    'nav.accueil': 'Home',
    'nav.apropos': 'About',
    'nav.competences': 'Skills',
    'nav.projets': 'Projects',
    'nav.contact': 'Contact me',

    'theme.professionnel': 'Professional',
    'theme.gaming': 'Gaming',
    'theme.personnel': 'Personal style',
    'theme.description-professionnel': 'Clean and efficient',
    'theme.description-gaming': 'A real playable game',
    'theme.description-personnel': 'Manga, pixels and neon',

    'footer.droits': 'All rights reserved.',
    'footer.cv': 'Download my resume',
    'footer.cv-demande': 'Request my resume',
    'footer.cv-sujet': 'Resume request',
    'footer.credits': 'Font Awesome icons (CC BY 4.0) · Google Fonts (OFL)',

    // ---------- Shared content ----------
    'profil.role-court': 'Junior Full Stack Developer',
    'apropos.titre': 'About me',
    'apropos.p1': "Passionate about computers and video games since childhood, I naturally turned that passion into a real professional path. After high school, I joined the Computer Science and Software Engineering program, where I am now in the second year of my bachelor's degree.",
    'apropos.p2': 'As a junior Full Stack developer, I design and build websites, applications and databases, from concept to production. I love turning ideas into concrete, functional and intuitive solutions.',
    'apropos.p3': 'Beyond development, I am into graphic design, 3D modeling, video editing and computer maintenance. These skills, which I grow alongside programming, let me build more complete projects where technology, creativity and craft meet.',
    'apropos.etudes': "Bachelor's year 2 · Computer Science and Software Engineering",
    'apropos.objectif': 'Goal: become an expert in video game development',
    'apropos.chiffre-competences': 'Skills',
    'apropos.chiffre-projets': 'Projects',
    'apropos.chiffre-annees': 'Years of experience',

    'competences.titre': 'My skills',
    'competences.niveau': 'Level:',
    'niveau.debutant': 'Beginner',
    'niveau.intermediaire': 'Intermediate',
    'niveau.expert': 'Expert',
    'categorie.web': 'Web',
    'categorie.logiciel': 'Software and mobile',
    'categorie.jeu': 'Games and 3D',
    'categorie.creation': 'Visual creation',
    'categorie.outil': 'Tools',
    'categorie.tout': 'All',
    'categorie.ia': 'AI',

    'projets.titre': 'My projects',
    'projets.code': 'Code',
    'projets.demo': 'Demo',
    'projets.code-prive': 'Private code',
    'projets.termine': 'Completed',
    'projets.vedette': 'Flagship project',
    'projets.encours': 'In progress',
    'projets.filtrer': 'Filter projects',
    'projets.voir-github': 'See everything on GitHub',
    'projets.capture-a-venir': 'Screenshot coming soon',

    'contact.titre': 'Contact me',
    'contact.sous-titre': 'An internship, a project, an idea? Write to me, I reply fast.',
    'contact.dispo': 'Available for any kind of internship, as well as interviews and freelance projects.',
    'contact.localisation': 'Location',
    'contact.formulaire-titre': 'Send me a message',
    'contact.label-nom': 'Name',
    'contact.label-email': 'Email',
    'contact.label-message': 'Message',
    'contact.placeholder-nom': 'Your name',
    'contact.placeholder-email': 'you@example.com',
    'contact.placeholder-message': 'Hi Jean-Marc, ...',
    'contact.bouton-envoyer': 'Send message',
    'contact.envoi-cours': 'Sending...',
    'contact.succes': 'Message sent successfully, thank you!',
    'contact.erreur': 'Something went wrong. Please try again or email me directly.',
    'contact.email': 'Email',
    'contact.whatsapp': 'WhatsApp',
    'contact.github': 'GitHub',

    // ---------- Professional theme ----------
    'pro.salutation': 'Welcome to my portfolio',
    'pro.jesuis': 'I am',
    'pro.role': 'Junior <span class="role-accent">Full Stack</span> Developer',
    'pro.accroche': 'I build websites, apps and games, from the first sketch to going live.',
    'pro.langage': 'Favorite language:',
    'pro.bouton-projets': 'View my projects',
    'pro.bouton-contact': 'Contact me',
    'pro.badge-experience': 'Years of experience',
    'pro.badge-projets': 'Completed projects',
    'pro.photo-alt': 'Photo of Gninoue Jean-Marc',
    'pro.defiler': 'Scroll down',
    'pro.essayer-theme': 'Want to see something else?',
    'pro.essayer-theme-texte': 'This portfolio comes in three versions. Try another one:',
    'pro.essayer-bouton': 'Try another portfolio theme',
    // ---------- Gaming theme: Island of Fragments ----------
    'jeu.titre': 'Island of Fragments',
    'jeu.sous-titre': 'A playable portfolio by Dev Gninoue',
    'jeu.intro': 'Night has swallowed the island. Bring the light back by finding the four fragments of the portfolio.',
    'jeu.jouer': 'Play',
    'jeu.continuer': 'Continue',
    'jeu.nouvelle-partie': 'New game',
    'jeu.mode-lecture': 'Skip the game / Reading mode',
    'jeu.mode-lecture-court': 'Reading mode',
    'jeu.retour-jeu': 'Back to the game',
    'jeu.chargement': 'Loading the island...',
    'jeu.duree': 'About 5 minutes · progress is saved',
    'jeu.controles': 'Controls',
    'jeu.controles-clavier': 'WASD or arrows: move · Shift: run · E or Space: interact · Esc: pause',
    'jeu.controles-souris': 'Mouse: click to move or interact',
    'jeu.controles-tactile': 'Touch: drag to move, tap to interact',
    'jeu.mouvement-reduit': 'Reduced motion: screen shake and flashes are off.',
    'jeu.libelle-canevas': 'Island of Fragments, an exploration game. The Reading mode button gives access to all the content without playing.',
    'jeu.son': 'Sound',
    'jeu.son-active': 'Sound on',
    'jeu.son-coupe': 'Sound off',
    'jeu.pause': 'Pause',
    'jeu.reprendre': 'Resume',
    'jeu.recommencer': 'Restart',
    'jeu.confirmer-recommencer': 'Click again to erase progress',
    'jeu.changer-theme': 'Change theme',
    'jeu.suivant': 'Next',
    'jeu.fermer': 'Close',
    'jeu.fragments': 'fragments',
    'jeu.fragment-histoire': 'Story',
    'jeu.fragment-savoir': 'Knowledge',
    'jeu.fragment-oeuvres': 'Works',
    'jeu.fragment-lien': 'Bond',
    'jeu.fragment-obtenu': 'Fragment found: {nom} ({n}/4)',
    'jeu.obtenu': 'obtained',
    'jeu.manquant': 'not obtained yet',
    'jeu.orbes': 'Skill orbs',
    'jeu.steles': 'Project monoliths',
    'jeu.objectif-village': 'Talk to the Archivist in the Village of Memories (About)',
    'jeu.objectif-foret': 'Collect the orbs in the Forest of Knowledge (Skills)',
    'jeu.objectif-ruines': 'Awaken the monoliths in the Ruins of Works (Projects)',
    'jeu.objectif-boss': 'The dome is broken: face the Great Bug at Lighthouse Cape',
    'jeu.objectif-fin': 'The island is saved! The lighthouse awaits to contact Dev',
    'jeu.zone-camp': 'The Campfire',
    'jeu.zone-camp-sous': 'Starting point',
    'jeu.zone-village': 'Village of Memories',
    'jeu.zone-village-sous': 'About',
    'jeu.zone-foret': 'Forest of Knowledge',
    'jeu.zone-foret-sous': 'Skills',
    'jeu.zone-ruines': 'Ruins of Works',
    'jeu.zone-ruines-sous': 'Projects',
    'jeu.zone-arene': 'Lighthouse Cape',
    'jeu.zone-arene-sous': 'Contact',
    'jeu.nom-panneau': 'Sign',
    'jeu.nom-archiviste': 'The Archivist',
    'jeu.nom-bug': 'The Great Bug',
    'jeu.nom-phare': 'The lighthouse',
    'jeu.panneau-camp': "Welcome, traveler! Dev's island is lost in the night. Three fragments await: the Village to the northwest, the Forest to the northeast and the Ruins to the southwest. If you get lost, follow the golden arrow.",
    'jeu.panneau-village': "Village of Memories. The Archivist keeps Dev's story here.",
    'jeu.panneau-foret': "Forest of Knowledge. Each glowing orb holds one of Dev's skills. Collect them all!",
    'jeu.panneau-ruines': 'Ruins of Works. Each monolith remembers a project: walk up and inspect them.',
    'jeu.panneau-arene': 'Lighthouse Cape. A dome of glitches blocks the way: three fragments are needed to break it.',
    'jeu.archiviste-1': 'Oh! A lit lantern, at last. Welcome, traveler. I am the Archivist: I keep the memory of the one who shaped this island.',
    'jeu.archiviste-2': 'His name is Gninoue Jean-Marc. Here we call him Dev... and OZEN when he plays games or edits videos. Listen to his story...',
    'jeu.archiviste-fin': 'That is his story. Take this fragment: it will bring some light back to the island.',
    'jeu.archiviste-retour': "You want to hear Dev's story again? With pleasure.",
    'jeu.orbe-obtenue': '{nom} · {niveau} ({n}/{total})',
    'jeu.dome-ferme': 'The dome holds. {n} fragment(s) still missing.',
    'jeu.dome-ouvert': 'Three fragments gathered: the dome over Lighthouse Cape has shattered!',
    'jeu.bug-1': 'Who dares to bring back the light? I am the Great Bug. I devoured this island\'s light, one line of code at a time.',
    'jeu.bug-2': "You'll never touch me... unless you charge the three light pylons. But you wouldn't dare!",
    'jeu.bug-3': '(Stand next to a pylon to charge it, and dodge the pink glitches.)',
    'jeu.phare-eteint': 'The lighthouse is dark. The Great Bug still prowls around the cape.',
    'jeu.action-parler': 'Talk',
    'jeu.action-lire': 'Read',
    'jeu.action-examiner': 'Inspect',
    'jeu.stele-progression': 'Monolith {n} of {total}',
    'jeu.fin-titre': 'The island is restored!',
    'jeu.fin-texte': 'Thanks for playing! You now know Dev: his story, his skills and his projects. Only one thing left to do...',
    'jeu.fin-contact': 'Contact Dev',
    'jeu.fin-temps': 'Time',
    'jeu.fin-succes': 'Achievements',
    'jeu.continuer-explorer': 'Keep exploring',
    'jeu.ecrire': 'Write a message',
    'jeu.succes-debloque': 'Achievement unlocked: {nom}',
    'jeu.lecture-titre': 'The portfolio, text version',
    'jeu.lecture-intro': 'No time to play? Everything is right here.',
    'jeu.credits': 'Island of Fragments: graphics and sounds generated in code · Press Start 2P and Pixelify Sans fonts (OFL)',
    'succes.premier-pas': 'First step',
    'succes.premier-pas-desc': 'Take your first steps on the island',
    'succes.bavard': 'Good listener',
    'succes.bavard-desc': "Hear the Archivist's story",
    'succes.explorateur': 'Explorer',
    'succes.explorateur-desc': 'Visit all four regions',
    'succes.collectionneur': 'Collector',
    'succes.collectionneur-desc': 'Collect every orb',
    'succes.archeologue': 'Archaeologist',
    'succes.archeologue-desc': 'Awaken every monolith',
    'succes.chasseur': 'Bug hunter',
    'succes.chasseur-desc': 'Defeat the Great Bug',
    'succes.intouchable': 'Untouchable',
    'succes.intouchable-desc': 'Defeat the Great Bug without getting hit',
    'succes.eclair': 'Lightning',
    'succes.eclair-desc': 'Finish the adventure in under 5 minutes',
    // ---------- Personal style theme ----------
    'perso.volume': 'Volume',
    'perso.sous-titre': 'Full Stack developer, video game creator and video editor',
    'perso.commandes': 'whoami --role fullstack|compile --lang c++ --mode passion|render --edit after-effects|git push origin dreams',
    'perso.lire-volumes': 'Read the volumes',
    'perso.ecrire': 'Write to me',
    'perso.bulle-bonjour': 'Welcome to my world!',
    'perso.tourner-page': 'Turn the page',
    'perso.chapitre': 'Chapter',
    'perso.fiche': 'Character sheet',
    'perso.fiche-nom': 'Name',
    'perso.fiche-classe': 'Class',
    'perso.fiche-niveau': 'Level',
    'perso.fiche-arme': 'Weapon of choice',
    'perso.fiche-quete': 'Main quest',
    'perso.fiche-animes': 'Anime and manga',
    'perso.fiche-jeux': 'Favorite games',
    'perso.fiche-devise': 'Motto',
    'perso.fiche-pseudo': 'Alias',
    'perso.fiche-pseudo-valeur': 'OZEN (in games and video editing)',
    'perso.fiche-origine': 'Home base',
    'perso.fiche-personnalite': 'In one sentence',
    'perso.fiche-tekken': 'Tekken mains',
    'perso.a-debloquer': 'Locked',
    'perso.filtrer-competences': 'Filter skills',
    'perso.legende': 'Power gauge: three segments per level (beginner, intermediate, expert).',
    'perso.intro-volumes': 'Each project is a volume of the series. Some are complete, others are still being published.',
    'perso.a-suivre': 'To be continued...',
    'perso.autre-dimension': 'This manga also exists in two other dimensions:',
    'perso.credits': 'Personal style: GSAP animations (GreenSock standard license) · Dela Gothic One, Zen Kaku Gothic New and Share Tech Mono fonts (OFL)'
  }
};
