// ============================================
// DICTIONNAIRE FR / EN
// Toutes les chaînes visibles du site, tous thèmes confondus.
// Utilisation : t('cle') depuis le JS, ou data-i18n="cle"
// (data-i18n-html, data-i18n-aria, data-i18n-title) dans le HTML.
// ============================================
const traductions = {
  fr: {
    // ---------- Commun ----------
    'commun.titre-page': 'Dev Gninoue — Portfolio',
    'commun.aller-contenu': 'Aller au contenu',
    'commun.ouvrir-menu': 'Ouvrir le menu',
    'commun.fermer-menu': 'Fermer le menu',
    'commun.nav-principale': 'Navigation principale',
    'commun.nav-pied': 'Liens du pied de page',
    'commun.choisir-langue': 'Choisir la langue',
    'commun.choisir-theme': 'Choisir le thème',
    'commun.whatsapp': 'Me contacter sur WhatsApp',
    'commun.whatsapp-message': 'Bonjour, je vous contacte depuis votre portfolio.',
    'commun.theme-change': 'Thème appliqué : {theme}',
    'commun.langue-change': 'Langue : français',
    'commun.erreur-theme': "Impossible de charger ce thème. Vérifiez votre connexion puis réessayez.",
    'commun.a-venir': 'Bientôt disponible',
    'commun.fermer': 'Fermer',
    'commun.nouvel-onglet': '(nouvel onglet)',

    'nav.accueil': 'Accueil',
    'nav.apropos': 'À propos',
    'nav.competences': 'Compétences',
    'nav.projets': 'Projets',
    'nav.contact': 'Me contacter',

    'theme.professionnel': 'Professionnel',
    'theme.gaming': 'Gaming',
    'theme.personnel': 'Style personnel',
    'theme.description-professionnel': 'Sobre et efficace',
    'theme.description-gaming': 'Un vrai jeu jouable',
    'theme.description-personnel': 'Manga, pixel et néon',

    'footer.droits': 'Tous droits réservés.',
    'footer.cv': 'Télécharger mon CV',
    'footer.cv-demande': 'Demander mon CV',
    'footer.cv-sujet': 'Demande de CV',
    'footer.credits': 'Icônes Font Awesome (CC BY 4.0) · Polices Google Fonts (OFL)',

    // ---------- Contenu partagé ----------
    'profil.role-court': 'Développeur Full Stack junior',
    'apropos.titre': 'À propos de moi',
    'apropos.p1': "Passionné par l'informatique et les jeux vidéo depuis l'enfance, j'ai naturellement choisi de transformer cette passion en véritable projet professionnel. Après l'obtention de mon baccalauréat, j'ai intégré la filière Informatique et Génie Logiciel, où je poursuis actuellement ma deuxième année de licence.",
    'apropos.p2': "En tant que développeur Full Stack junior, je conçois et développe des sites web, des applications et des bases de données, de la conception à la mise en production. J'aime transformer des idées en solutions concrètes, fonctionnelles et intuitives.",
    'apropos.p3': "Au-delà du développement, je m'intéresse au graphisme, à la modélisation 3D, au montage vidéo et à la maintenance informatique. Ces compétences, que je développe en complément de la programmation, me permettent de créer des projets plus complets, à la croisée de la technologie, de la créativité et de la technique.",
    'apropos.etudes': 'Licence 2 · Informatique et Génie Logiciel',
    'apropos.objectif': 'Objectif : devenir expert en développement de jeux vidéo',
    'apropos.chiffre-competences': 'Compétences',
    'apropos.chiffre-projets': 'Projets',
    'apropos.chiffre-annees': "Ans d'expérience",

    'competences.titre': 'Mes compétences',
    'competences.niveau': 'Niveau :',
    'niveau.debutant': 'Débutant',
    'niveau.intermediaire': 'Intermédiaire',
    'niveau.expert': 'Expert',
    'categorie.web': 'Web',
    'categorie.logiciel': 'Logiciel et mobile',
    'categorie.jeu': 'Jeu vidéo et 3D',
    'categorie.creation': 'Création visuelle',
    'categorie.outil': 'Outils',
    'categorie.tout': 'Tout',
    'categorie.ia': 'IA',

    'projets.titre': 'Mes projets réalisés',
    'projets.code': 'Code',
    'projets.demo': 'Démo',
    'projets.code-prive': 'Code privé',
    'projets.termine': 'Terminé',
    'projets.encours': 'En cours',
    'projets.filtrer': 'Filtrer les projets',
    'projets.voir-github': 'Voir tout sur GitHub',
    'projets.capture-a-venir': 'Capture à venir',

    'contact.titre': 'Me contacter',
    'contact.sous-titre': 'Un stage, un projet, une idée ? Écrivez-moi, je réponds vite.',
    'contact.dispo': 'Disponible pour des stages, des entretiens et des projets freelance.',
    'contact.formulaire-titre': "M'envoyer un message",
    'contact.label-nom': 'Nom',
    'contact.label-email': 'Email',
    'contact.label-message': 'Message',
    'contact.placeholder-nom': 'Votre nom',
    'contact.placeholder-email': 'vous@exemple.com',
    'contact.placeholder-message': 'Bonjour Jean-Marc, ...',
    'contact.bouton-envoyer': 'Envoyer le message',
    'contact.envoi-cours': 'Envoi en cours...',
    'contact.succes': 'Message envoyé avec succès, merci !',
    'contact.erreur': "Une erreur s'est produite. Réessayez ou écrivez-moi directement par email.",
    'contact.email': 'Email',
    'contact.whatsapp': 'WhatsApp',
    'contact.github': 'GitHub',

    // ---------- Thème Professionnel ----------
    'pro.salutation': 'Bienvenue sur mon portfolio',
    'pro.jesuis': 'Je suis',
    'pro.role': 'Développeur <span class="role-accent">Full Stack</span> Junior',
    'pro.accroche': 'Je conçois des sites, des applications et des jeux, du premier croquis à la mise en ligne.',
    'pro.langage': 'Langage favori :',
    'pro.bouton-projets': 'Voir mes projets',
    'pro.bouton-contact': 'Me contacter',
    'pro.badge-experience': "Ans d'expérience",
    'pro.badge-projets': 'Projets réalisés',
    'pro.photo-alt': 'Photo de Gninoue Jean-Marc',
    'pro.defiler': 'Défiler vers la suite',
    'pro.essayer-theme': 'Envie de voir autre chose ?',
    'pro.essayer-theme-texte': 'Ce portfolio existe en trois versions. Essayez-en une autre :',
    'pro.essayer-bouton': 'Essayer un autre thème du portfolio'
  },

  en: {
    // ---------- Common ----------
    'commun.titre-page': 'Dev Gninoue — Portfolio',
    'commun.aller-contenu': 'Skip to content',
    'commun.ouvrir-menu': 'Open menu',
    'commun.fermer-menu': 'Close menu',
    'commun.nav-principale': 'Main navigation',
    'commun.nav-pied': 'Footer links',
    'commun.choisir-langue': 'Choose language',
    'commun.choisir-theme': 'Choose theme',
    'commun.whatsapp': 'Contact me on WhatsApp',
    'commun.whatsapp-message': 'Hello, I am reaching out from your portfolio.',
    'commun.theme-change': 'Theme applied: {theme}',
    'commun.langue-change': 'Language: English',
    'commun.erreur-theme': 'Could not load this theme. Check your connection and try again.',
    'commun.a-venir': 'Coming soon',
    'commun.fermer': 'Close',
    'commun.nouvel-onglet': '(new tab)',

    'nav.accueil': 'Home',
    'nav.apropos': 'About',
    'nav.competences': 'Skills',
    'nav.projets': 'Projects',
    'nav.contact': 'Contact me',

    'theme.professionnel': 'Professional',
    'theme.gaming': 'Gaming',
    'theme.personnel': 'Personal style',
    'theme.description-professionnel': 'Clean and efficient',
    'theme.description-gaming': 'A real playable game',
    'theme.description-personnel': 'Manga, pixels and neon',

    'footer.droits': 'All rights reserved.',
    'footer.cv': 'Download my resume',
    'footer.cv-demande': 'Request my resume',
    'footer.cv-sujet': 'Resume request',
    'footer.credits': 'Font Awesome icons (CC BY 4.0) · Google Fonts (OFL)',

    // ---------- Shared content ----------
    'profil.role-court': 'Junior Full Stack Developer',
    'apropos.titre': 'About me',
    'apropos.p1': "Passionate about computers and video games since childhood, I naturally turned that passion into a real professional path. After high school, I joined the Computer Science and Software Engineering program, where I am now in the second year of my bachelor's degree.",
    'apropos.p2': 'As a junior Full Stack developer, I design and build websites, applications and databases, from concept to production. I love turning ideas into concrete, functional and intuitive solutions.',
    'apropos.p3': 'Beyond development, I am into graphic design, 3D modeling, video editing and computer maintenance. These skills, which I grow alongside programming, let me build more complete projects where technology, creativity and craft meet.',
    'apropos.etudes': "Bachelor's year 2 · Computer Science and Software Engineering",
    'apropos.objectif': 'Goal: become an expert in video game development',
    'apropos.chiffre-competences': 'Skills',
    'apropos.chiffre-projets': 'Projects',
    'apropos.chiffre-annees': 'Years of experience',

    'competences.titre': 'My skills',
    'competences.niveau': 'Level:',
    'niveau.debutant': 'Beginner',
    'niveau.intermediaire': 'Intermediate',
    'niveau.expert': 'Expert',
    'categorie.web': 'Web',
    'categorie.logiciel': 'Software and mobile',
    'categorie.jeu': 'Games and 3D',
    'categorie.creation': 'Visual creation',
    'categorie.outil': 'Tools',
    'categorie.tout': 'All',
    'categorie.ia': 'AI',

    'projets.titre': 'My projects',
    'projets.code': 'Code',
    'projets.demo': 'Demo',
    'projets.code-prive': 'Private code',
    'projets.termine': 'Completed',
    'projets.encours': 'In progress',
    'projets.filtrer': 'Filter projects',
    'projets.voir-github': 'See everything on GitHub',
    'projets.capture-a-venir': 'Screenshot coming soon',

    'contact.titre': 'Contact me',
    'contact.sous-titre': 'An internship, a project, an idea? Write to me, I reply fast.',
    'contact.dispo': 'Available for internships, interviews and freelance projects.',
    'contact.formulaire-titre': 'Send me a message',
    'contact.label-nom': 'Name',
    'contact.label-email': 'Email',
    'contact.label-message': 'Message',
    'contact.placeholder-nom': 'Your name',
    'contact.placeholder-email': 'you@example.com',
    'contact.placeholder-message': 'Hi Jean-Marc, ...',
    'contact.bouton-envoyer': 'Send message',
    'contact.envoi-cours': 'Sending...',
    'contact.succes': 'Message sent successfully, thank you!',
    'contact.erreur': 'Something went wrong. Please try again or email me directly.',
    'contact.email': 'Email',
    'contact.whatsapp': 'WhatsApp',
    'contact.github': 'GitHub',

    // ---------- Professional theme ----------
    'pro.salutation': 'Welcome to my portfolio',
    'pro.jesuis': 'I am',
    'pro.role': 'Junior <span class="role-accent">Full Stack</span> Developer',
    'pro.accroche': 'I build websites, apps and games, from the first sketch to going live.',
    'pro.langage': 'Favorite language:',
    'pro.bouton-projets': 'View my projects',
    'pro.bouton-contact': 'Contact me',
    'pro.badge-experience': 'Years of experience',
    'pro.badge-projets': 'Completed projects',
    'pro.photo-alt': 'Photo of Gninoue Jean-Marc',
    'pro.defiler': 'Scroll down',
    'pro.essayer-theme': 'Want to see something else?',
    'pro.essayer-theme-texte': 'This portfolio comes in three versions. Try another one:',
    'pro.essayer-bouton': 'Try another portfolio theme'
  }
};
